app/__init__.py
"""SVM_Loss: Linear Classifier and Loss function demo.

A web application to demonstrate back-prop based optimization of
a linear classifier

:license: Apache 2, see LICENSE for more details.
"""

import os
from datetime import datetime
import logging
from logging.handlers import RotatingFileHandler
from flask import Flask, abort, current_app
from flask_bootstrap import Bootstrap
from flask_cors import CORS

from config import config_list

__version__ = "0.1.dev"

bootstrap = Bootstrap()

env_ = os.environ.get('SVM_LOSS_CONF', 'development')

if env_ in config_list:
    config_val = config_list[env_]
else:
    raise EnvironmentError('Cannot find environment config')


def get_operation_years() -> str:
    """Return a string representing the operation years of the website."""
    start_year = int(current_app.config['START_YEAR'])
    current_year = int(datetime.now().year)
    if start_year == current_year:
        return str(start_year)
    else:
        return ' - '.join([str(start_year), str(current_year)])


def create_app(config_class: object = config_val):
    """Create and configure the instance of the application."""
    app = Flask(__name__)
    app.config.from_object(config_class)

    bootstrap.init_app(app)
    CORS(app)

    from app.demo import bp as demo_bp
    app.register_blueprint(demo_bp)

    from app.errors import bp as errors_bp
    app.register_blueprint(errors_bp)

    # Set up the logger to work only in production
    if not app.debug and not app.testing:
        if not os.path.exists('logs'):
            os.mkdir('logs')
        file_handler = RotatingFileHandler('logs/svm_loss.log',
                                           maxBytes=10240, backupCount=10)
        file_handler.setFormatter(logging.Formatter(
            '%(asctime)s %(levelname)s: %(message)s '
            '[in %(pathname)s:%(lineno)d]'))
        file_handler.setLevel(logging.INFO)
        app.logger.addHandler(file_handler)

        app.logger.setLevel(logging.INFO)
        app.logger.info('SVM_Loss startup')

    @app.context_processor
    def inject_global_vars():
        """Inject global variables to be used, e.g., in Jinja templates."""
        return dict(
            site_name=app.config['SITE_NAME'],
            operation_years=get_operation_years(),
            app_config=app.config)

    @app.route('/ping')
    def ping():
        """Render a simple ping message."""
        return 'Ping!'

    @app.route('/err500')
    def err500():
        """Simulate a 500 error."""
        abort(500)

    return app

app/demo/__init__.py
"""Initializes the Demo package."""

from app.demo.blueprint import bp
from app.demo import routes

_all = [bp, routes]

app/demo/blueprint.py
"""Defines the blueprint for the Demo package."""

from flask import Blueprint

bp = Blueprint('demo', __name__, template_folder='../templates/demo', )

app/demo/routes.py
"""Routes for the Demo package."""
from builtins import isinstance

import numpy as np
from numpy import ndarray
import json
from json import JSONDecodeError
from flask import render_template, jsonify, request, send_from_directory, \
    make_response, redirect
from flask_cors import cross_origin

from app.demo import bp
from app.demo.optimizer import grad_step, adjust_params
from app.demo.utils import (
    get_urls,
    init_data,
    init_params,
    is_int
)
from app.demo.plot import (
    generate_plot_image_string
)

from config import client_dir

@bp.route('/flask', methods=['GET'])
def flask():
    """Serve the main route for the application."""
    urls = get_urls()
    return render_template('index.html', urls=urls)


@bp.route('/', methods=['GET'])
@bp.route('/index', methods=['GET'])
def index():
    """Serve the main route for the application."""
    #urls = get_urls()
    #return render_template('index.html', urls=urls)
    return redirect('/client/', 301)


@bp.route('/client', methods=['GET'])
def clientNoSlash():
    return redirect('/client/', 301)

@bp.route('/client/', methods=['GET'])
def client():
    """Serve the client React app."""
    return send_from_directory(client_dir, 'index.html')


@bp.route('/client/<path:path>', methods=['GET'])
def client_path(path):
    """Serve the client React app."""
    return send_from_directory(client_dir, path)


@bp.route('/get_params', methods=['GET'])
@cross_origin()
def get_params() -> str:
    """Return a json string with init or random parameters."""
    rand = False
    if not request.args.get('rand') is None and is_int(
            request.args.get('rand')):
        rand = bool(int(request.args.get('rand')))
    resp = make_response(jsonify(init_params(rand)), 200)
    return resp


@bp.route('/get_data', methods=['GET'])
@cross_origin()
def get_data() -> str:
    """Return a json string with training data to be classified."""
    rand = False
    if not request.args.get('rand') is None and is_int(
            request.args.get('rand')):
        rand = bool(int(request.args.get('rand')))

    resp = make_response(jsonify(init_data(rand)), 200)
    return resp


@bp.route('/get_plot', methods=['POST', 'OPTIONS'])
@cross_origin()
def get_plot():
    """Return a base64 encoded content of the plot."""
    try:
        if request.is_json:
            data = request.json.get('data')
            params = request.json.get('params')
        else:
            data = json.loads(request.form.get('data'))
            params = json.loads(request.form.get('params'))
        if not isinstance(params, dict) or not isinstance(data, list):
            raise TypeError('Invalid data')
        data = np.array(data)

        weights = params['weights']
        biases = params['biases']

        params_ = np.c_[weights, biases]

        plot = generate_plot_image_string(data, params_)
        resp = make_response(jsonify({'plot': plot}), 200)
    except JSONDecodeError as ex:
        resp = make_response(
            jsonify({'error': ', '.join(['Invalid data: ', str(ex)])}), 500)
    except TypeError as ex:
        resp = make_response(jsonify({'error': str(ex)}), 500)
    except KeyError as ex:
        resp = make_response(
            jsonify({'error': ', '.join(['Missing key: ', str(ex)])}), 500)
    return resp


@bp.route('/get_step', methods=['POST'])
def get_step():
    """Perform a single optimization step."""
    try:
        if request.is_json:
            data = request.json.get('data')
            params = request.json.get('params')
            hyper = request.json.get('hyper')
        else:
            data = json.loads(request.form.get('data'))
            params = json.loads(request.form.get('params'))
            hyper = json.loads(request.form.get('hyper'))

        if not isinstance(params, dict) or not isinstance(data, list) \
                or not isinstance(hyper, dict):
            raise TypeError('Invalid data')
        data = np.array(data)

        weights = params['weights']
        biases = params['biases']
        labels = data[:, -1].astype(int)
        params_ = np.c_[weights, biases]

        result = dict()

        result['grad_w'], result['grad_b'], result['cost_loss'], \
        result['loss'], result['scores'], result['total_loss'], \
        result['reg_loss'] = grad_step(data, labels, params_,
                                       hyper['loss_type'], float(hyper['reg_c']))

        weights = np.array(weights)
        biases = np.array(biases)
        if len(biases.shape) == 1:
            biases = biases[:, np.newaxis]

        result['weights'], result['biases'] = \
            adjust_params(weights, biases, result['grad_w'], result['grad_b'],
                          hyper['learning_rate'])

        # Convert ndarrays to lists before jsonifying
        result = {key: (lambda x: x.tolist() if isinstance(x, ndarray) else x)(
            result[key]) for key in result}

        plot = generate_plot_image_string(data, np.c_[
            result['weights'], result['biases']])
        result['plot'] = plot

        result['mean_loss'] = np.mean(result['loss'])

        return jsonify(result)

    except JSONDecodeError as ex:
        return jsonify({'error': ', '.join(['Invalid data: ', str(ex)])})
    except TypeError as ex:
        return jsonify({'error': str(ex)})
    except KeyError as ex:
        return jsonify({'error': ', '.join(['Missing key: ', str(ex)])})
    except ValueError as ex:
        return jsonify({'error': str(ex)})

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}
    {{ title|default(site_name) }}
{% endblock %}


{% block metas %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
{% endblock %}

{% block styles %}
    {{ super() }}
    <link href="https://fonts.googleapis.com/css?family=Varela+Round&display=swap"
          rel="stylesheet">

    <link href="{{ url_for('static', filename='vendor/fontawesome-free/css/all.min.css') }}"
          rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    <link href="{{ url_for('static', filename='css/sb-admin-2.min.css') }}"
          rel="stylesheet">
    <link href="{{ url_for('static', filename='overrides/css/overrides.css') }}"
          rel="stylesheet">
    <link href="{{ url_for('static', filename='overrides/css/layout.css') }}"
          rel="stylesheet">
{% endblock %}

{% block body_attribs %} id="page-top" {% endblock %}


{% block content %}
    <!-- Page Wrapper -->
    <div class="wrapper">

        {% block content_wrapper %}
            <!-- Content Wrapper -->
                {% block main_content %}
                {% endblock %}

                {% block footer %}
                    {% include 'footer.html' %}
                {% endblock %}

            <!-- End of Content Wrapper -->
        {% endblock %}

    </div>
    <!-- End of Page Wrapper -->

    {% block scroll_to_top %}
        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top">
            <i class="fas fa-angle-up"></i>
        </a>
        <!-- End scroll to Top Button-->
    {% endblock %}

    {% block logout_modal %}
        <!-- empty logout block -->
    {% endblock %}

{% endblock %}


{% block scripts %}

    <!-- Bootstrap core JavaScript-->
    <script src="{{ url_for('static', filename='vendor/jquery/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{{ url_for('static', filename='vendor/jquery-easing/jquery.easing.min.js') }}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{{ url_for('static', filename='js/sb-admin-2.min.js') }}"></script>

    <!-- MathJax integration -->
    <script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML'
            async></script>

    <!-- custom Demo code -->
    <script src="{{ url_for('static', filename='overrides/js/demo.js') }}"></script>


    <script>
        const defErrorTitle = 'Error',
            defErrorMessage = 'An error has occurred.';
    </script>

{% endblock %}

app/templates/footer.html
<!-- start footer -->
<footer class="footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; {{ site_name }} {{ operation_years }}</span>
        </div>
    </div>
</footer>
<!-- end footer -->

app/templates/index.html
{% extends "base.html" %}

{% block title %}
    {{ title|default(site_name) }}
{% endblock %}

{% block body_attribs %} id="page-top"
    class="bg-white" {% endblock %}

{% block main_content %}

    <header class="masthead bg-white">
        <div class="mx-auto text-center">
            <h1 class="mx-auto my-4 text-uppercase text-gray-700">{{ site_name }}</h1>
            <h2 class="text-gray-900 mx-auto mt-2 mb-5">
                Linear Classifier Demo
            </h2>

        </div>
    </header>
    <div class="content-wrapper">
        <div class="intro card shadow">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">{{ 'background
                        of the demo' | title }}</h6>
            </div>
            <div class="card-body">
                {% include 'index/intro.html' %}
            </div>
        </div>
        <div class="visualization card shadow">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">{{ 'Data and
                        Classifier Visualization' | title }}</h6>
            </div>
            <div class="card-body">
                {% include 'index/left.html' %}
            </div>
        </div>
        <div class="params card shadow">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">{{ 'Classifier
                        parameters' | title }}</h6>
            </div>
            <div class="card-body">
                {% include 'index/center.html' %}
            </div>
        </div>
        <div class="datapoints card shadow">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">{{ 'Data point
                        and Loss values' | title }}</h6>
            </div>
            <div class="card-body">
                {% include 'index/right.html' %}
            </div>
        </div>
    </div>

    <script>
        const getParamsUrl = '{{ urls.get_params_url }}',
            getDataUrl = '{{ urls.get_data_url }}',
            getPlotUrl = '{{ urls.get_plot_url }}',
            getStepUrl = '{{ urls.get_step_url }}'
    </script>

{% endblock %}

app/templates/index/center.html
{% import 'macros/param.html' as param %}

<article>
    <p>
        Parameters \(W\), \(b\) are shown below. The value is in <b>bold</b> and
        its gradient
        (computed with backprop) is in <span class="text-red font-italic">red, italic</span>
        below. Click the triangles to
        control the parameters.
    </p>

    {% for i in range(0, 3) %}
    <div class="row">
        {% for y in range(0, 3) %}
        <div class="col-xs-4 p-1">{{ param.param(i, y) }}</div>
        {% endfor %}
    </div>
    {% endfor %}

    <div>
        <a href="javascript:demoObj.getParams(1)" class="btn btn-primary">Randomize
            params</a>
    </div>


</article>

app/templates/index/intro.html
<aticle class="text">
    <p>This projects implements the visualization of optimization loss for a
        linear multiclass classifier using Python and Flask. The idea is based
        on the <b>Multiclass Linear
            Classification Optimization Loss Visualization</b> <a
                href="http://vision.stanford.edu/teaching/cs231n-demos/linear-classify/"
                target="_blank">web demo</a> by Justin Johnson. The text below is
        taken from that demo page as well.</p>
    <hr>
    <p>
        The class scores for linear classifiers are computed as
        \(f(x_i;W,b)=Wx_i+b\),
        where the parameters consist of weights \(W\) and biases \(b\). The
        training
        data is \(x_i\) with labels \(y_i\). In this demo, the datapoints
        \(x_i\) are
        2-dimensional and there are 3 classes, so the weight matrix is of size
        \([3 \times 2]\) and the bias vector is of size \([3 \times 1]\). The
        multiclass loss
        function can be formulated in many ways. The default in this demo is an
        SVM that follows [Weston and Watkins 1999]. Denoting \(f\) as the \([3
        \times 1]\)
        vector that holds the class scores, the loss has the form:
    </p>
    <p style="width:100%; overflow-x:auto">
        $$L= \underbrace{\frac{1}{N}\sum_{i=1}^{N}\sum_{j\neq y_i} max(0, f_j -
        f_{y_i} + 1)}_{\text{data loss}} + \underbrace{\sum_k\sum_l
        W_{k,l}^2}_{\text{regularization loss}}$$
    </p>
    <p>
        Where \(N\) is the number of examples, and \(λ\) is a hyperparameter that
        controls the strength of the \(L2\) regularization penalty \(R(W)=\sum_k\sum_l W_{k, l}^2\).
        On the bottom right of this demo you can also flip to different
        formulations for the Multiclass SVM including One vs All (OVA) where a
        separate binary SVM is trained for every class independently (vs. other
        classes all labeled as negatives), and Structured SVM which maximizes
        the margin between the correct score and the score of the highest
        runner-up class. You can also choose to use the cross-entropy loss which
        is used by the Softmax classifier.
    </p>
</aticle>

app/templates/index/left.html
<article>
    <p>Datapoints are shown as circles colored by their class (red/green/blue).
        The background regions are colored by whichever class is most likely at
        any point according to the current weights.</p>

    <p>Each classifier is
        visualized by a line that indicates its zero score level set. For
        example, the blue classifier computes scores as
        \(W_{0,0}x_0+W_{0,1}x_1+b_0\) and the
        blue line shows the set of points \((x_0,x_1)\) that give score of zero.
        The
        blue arrow draws the vector \((W_{0,0},W_{0,1})\), which shows the
        direction of
        score increase and its length is proportional to how steep the increase
        is.</p>
</article>

<article>
    <div class="mb-4">
        <img id="plot" class="img-fluid"
        />
    </div>
</article>

<hr>

<div>
    <h4>Optimize</h4>
    <p>Iterations: <span data-target="iterations">0</span></p>

    <div class="row" onchange="demoObj.updateHyperParams()">
        <div class="col-xl-3 col-md-4 col-sm-4 col-xs-4 mb-4 form-group" style="align-self:flex-end">
            <label>Loss formulation</label>
            <select name="loss_type" class="form-control form-control-sm">
                <option value="ww">Weston Watkins 1999</option>
                <option value="ova">One-vs-All</option>
            </select>
        </div>

        <div class="col-xl-3 col-md-4 col-sm-4 col-xs-4 mb-4 form-group" style="align-self:flex-end">
            <label>Learning rate</label>
            <input name="learning_rate" class="form-control form-control-sm"
                   type="number" step="0.1" min="0" value="0.1">
        </div>

        <div class="col-xl-3 col-md-4 col-sm-4 col-xs-4 mb-4 form-group" style="align-self:flex-end">
            <label>Regularization strength</label>
            <input name="reg_c" class="form-control form-control-sm"
                   type="number" step="0.1" min="0" value="0.1">
        </div>

    </div>
    <a href="javascript:void(0)"
       onclick="demoObj.getStep()"
       class="btn btn-primary mr-1 mb-2">Single step</a>

    <a href="javascript:void(0)"
       onclick="demoObj.startContinuousUpdate()"
       class="btn btn-primary mr-1 mb-2">Start auto update</a>

    <a href="javascript:void(0)"
       onclick="demoObj.stopContinuousUpdate()"
       class="btn btn-primary mr-1 mb-2">Stop auto update</a>


</div>

app/templates/index/right.html
<article>
    <p>
        Each row is loss due to one
        datapoint. The first three columns are the 2D data \(x_i\) and the label
        \(y_i\).
        The next three columns are the three class scores from each classifier
        \(f(x_i;W,b)=Wx_i+b\) (E.g. s[0] = x[0] * W[0,0] + x[1] * W[0,1] +
        b[0]). The
        last column is the data loss for a single example, \(L_i\).
    </p>
    <div class="w-100" style="overflow-y:auto">
        <table class="table small">
            <thead>
            <tr>
                <th>X[0]</th>
                <th>X[1]</th>
                <th class="border-right">y</th>
                <th>s[0]</th>
                <th>s[1]</th>
                <th class="border-right">s[2]</th>
                <th>L</th>
            </tr>
            </thead>
            <tbody>
            {% for i in range(0,9) %}
            <tr>
                <td data-target="x-{{ i }}-0"></td>
                <td data-target="x-{{ i }}-1"></td>
                <td data-target="y-{{ i }}" class="border-right"></td>
                <td data-target="s-{{ i }}-0"></td>
                <td data-target="s-{{ i }}-1"></td>
                <td data-target="s-{{ i }}-2" class="border-right"></td>
                <td data-target="L-{{ i }}"></td>
            </tr>
            {% endfor %}
            <tr>
                <td colspan="5"></td>
                <td>Mean:</td>
                <td data-target="mean_loss"></td>
            </tr>

            </tbody>
        </table>

        <hr>
        <table class="table">
            <tbody>
            <tr>
                <td>Total data loss</td>
                <td data-target="mean_loss"></td>
            </tr>
            <tr>
                <td>Regularization loss</td>
                <td data-target="reg_loss"></td>
            </tr>
            <tr>
                <td>Total loss</td>
                <td data-target="total_loss"></td>
            </tr>
            </tbody>
        </table>
    </div>

    <div>
        <a href="javascript:demoObj.getTrainData(1)" class="btn btn-primary">Randomize
            data</a>
    </div>
</article>

app/templates/macros/param.html
{% macro param(x, y) %}

<div class="form-group">
    <label class="small">{% if y < 2 %}W [{{ x }}, {{ y }}]{% else %}b[{{ x
        }}]{% endif
        %} </label>
    <input type="number" step="1"
           class="form-control form-control-sm"
           data-source="{% if y < 2 %}w{{ x }}-{{ y }}{% else %}b-{{x}}{% endif %}">
    <span class="d-block text-red font-italic small"
          data-target="grad-{% if y < 2 %}w{{ x }}-{{ y }}{% else %}b-{{x}}{% endif %}">0</span>
</div>
{%- endmacro %}

app/templates/navbar.html
<nav class="error-header navbar navbar-light fixed-top p-4" id="mainNav">
    <h1><a class="navbar-brand js-scroll-trigger" href="{{ url_for('demo.index') }}">{{ site_name
            }}</a>
    </h1>
</nav>